### PR TITLE
Document the upgrade process

### PR DESCRIPTION
**Pull request by dmakarov**

### CODE REVIEW

**Comment by jackcmay** [comment]
Looking good.  Think it's possible for us to create git patches for the sysroot changes that would allow us to apply them blindly and if that fails then we go back, fix the merge, and update the patch?

**Comment by dmakarov** [comment]
git patches is git format-patch ( https://git-scm.com/docs/git-format-patch  ) or something else?  I thought about it, but it seems not to have an advantage over cherry picking. Cherry picking can be done semi-automatically if the structure of the changes is suitable for that. And the parches live in the git database anyway.

**Comment by jackcmay** [comment]
Can we write a script to apply the cherry-picks and bail if there is an issue?

**Comment by dmakarov** [comment]
Let's see the next time we do the upgrade what the script might be. Currently it seems it would take just a couple of git commands to apply the cherry-picked commits.

**Comment by dmakarov** [comment]
I'll also refine the process and the documentation of it over next iterations of the upgrades, hopefully automating it over time.

**Pull request merged**
